### ISSUE TITLE
This does not actually get the shortest number

### ISSUE THREAD

**Issue by aleks-hyf** [bengu-thon-mai-mochi/hyf-homework#12]
https://github.com/bengu-thon-mai-mochi/hyf-homework/blob/7acf66ea7a0ecd0de3feea55a16342c30967bdba/javascript/javascript2/week1/shortest-word.js#L3

You're only comparing with the element at index 0. Instead, you should memorize the index that contains the shortest string, and compare against _that_ index.

**Comment by bengu-thon-mai-mochi** [comment]
But isn't that index 0 re-assigned to newest shorter one in each loop iteration?

**Comment by aleks-hyf** [comment]
So i could be wrong - i'm not running the code, just looking at it :) If you run it and it works, all good. But it seems to me that you should be comparing `arr[i].length < word.length`, because when you assign `word = arr[i]` , it no longer points to the 0th element of the array.

**Comment by bengu-thon-mai-mochi** [comment]
Now after spending a bit more time on it, I understand what you're pointing out to better.

I realized my main mistake handling homework exercises is that I initially do them very example specific. My code works for this kind of array and also the other median exercise you gave feedback works. But I what I take from your feedback is that there is best practices/logic for this kind of exercises. I will try to refactor my codes with this in mind.

Do you have any good article/tutorial that captures this kind of best practices for this sort of exercises?

Thank you!

**Comment by aleks-hyf** [comment]
No actually this is not a "best practices" comment. I still feel like this might be incorrect code, and you should understand why.  Your code doesn't actually work for the array: ['plante', 'kaffe', 'bog', 'op', 'planetarium']; But it does if you compare `arr[i].length < word.length`. (Now i actually played around with it in the code editor, because i had to make sure it makes sense)

**Comment by bengu-thon-mai-mochi** [comment]
https://imgur.com/a/ww9YARC
Now I am doubting my debugging tools.

**Comment by aleks-hyf** [comment]
One of us has to be right :) Maybe i gave you the wrong array, but for this:
`const danishWords = ['plante', 'kaffe', 'bog', 'a', 'op', 'planetarium'];` 

I get 'op' with your code, while it should be 'a'

**Comment by bengu-thon-mai-mochi** [comment]
I was sure you were right. I was trying to make sense of it through an example 🍡 

Now I have an example to decipher what I was doing wrong better. Thank you.

**Comment by aleks-hyf** [comment]
Aah perfect, so i'm not going mad then :)

**Comment by bengu-thon-mai-mochi** [comment]
I fixed it :) Thank you!!

**Comment by KalpanaHYF** [comment]
I see just now, Aleks already helped you with feedback, great to see both of your communication :) and loved to see short and sweet working code. happy coding!
