### ISSUE TITLE
good job

### ISSUE THREAD

**Issue by aleks-hyf** [bengu-thon-mai-mochi/hyf-homework#14]
https://github.com/bengu-thon-mai-mochi/hyf-homework/blob/1983d82be8bb1d8b49a940b9dc8c1b38fb02a2bc/javascript/javascript2/week2/movies.js#L44638

Easy to read, good indentation, and working code. Of course you should learn how to json out of the code and into another file, eventually.

**Comment by bengu-thon-mai-mochi** [comment]
Thanks, I will look into Json this week :)
