### ISSUE TITLE
JS3 week2

### ISSUE THREAD

**Issue by KalpanaHYF** [bengu-thon-mai-mochi/hyf-homework#19]
In rewrite settime function as a promise: 
you declared it as ....  const setTimeoutPromise = ...........
and you are calling with parameter (4 ) like normal function
setTimeoutPromise(4)
 signature of function doesnt match
1. so this can not be the case,  it should match isnt it ? this is just hint..
2. immediately create new instance or create promise ...this is another hint :)
and after that use then keyword to call the promise.
The rest of the code is correct.

**Comment by bengu-thon-mai-mochi** [comment]
Oh I understand so it should itself be a function that returns a promise? 

I implemented this changes to github. 

Thank you!

**Comment by KalpanaHYF** [comment]
yes, done well!

**Comment by KalpanaHYF** [comment]
done very well i guess visualPromise exc is pending. plz confirm.
