### ISSUE TITLE
Homework feedback - HTML/CSS - week 3

### ISSUE THREAD

**Issue by senner008** [bengu-thon-mai-mochi/hyf-homework#2]
Hi 
Great homework!
Please look at the comments and update.
Great that you manage to add pattern validation. Try to add more.
Lots of great stuff
Keep it up!

**Comment by bengu-thon-mai-mochi** [comment]
Hello Niels,
Thanks for the review!
I pushed the changes in both homeworks.
Sorry I forgot to update you about this.
Best,
Bengü
