### ISSUE TITLE
Homework feedback - JavaScript1/week1

### ISSUE THREAD

**Issue by Swapna-Sahu** [bengu-thon-mai-mochi/hyf-homework#3]
Hej Bengu,
Good job ! You have almost did great work in homework. You are very fast :)

I have few comments on your homework which needs to fix.

1. Task  - Goodboy-Oldboy (A dog age calculator)
Dog's age as per human years old logic is missing. It will be something like this:
let ageInHumanYear = dogYearFuture - dogYearOfBirth; 
let ageOfDog =  ageInHumanYear * 7 ;
2. Task  - Goodboy-Oldboy (A dog age calculator)
line 36 - you do not need to write (shouldShowResultInDogYears = true)
because it always takes true. So change it like this : 
let shouldShowResultInDogYears = false;
if(shouldShowResultInDogYears)

**Comment by bengu-thon-mai-mochi** [comment]
Hi Swampa 
I pushed the changes
best
bengü
