### ISSUE TITLE
Homework Feedback JS1-Week2

### ISSUE THREAD

**Issue by ovbm** [bengu-thon-mai-mochi/hyf-homework#4]
Hi Bengü, 
Here's the feedback for your homework:

Event-Calendar
Your solution is creative and it works. The task asked you to investigate remainder operators, which could have simplified your solution a little bit:
`let dayOfTheEvent = weekDay[(n % 7)-1];`
You can find out more about the modulo operator (%) [here](http://wiki.ecmascript.org/doku.php?id=strawman:modulo_operator).

Student-Manager
You were nearly there, the only problem was that you created stored a function for numberOfStudents constant instead of assigning the values directly to the constant. Which meant when you called numberOfStudents, it returned a function rather than the return value. If you replace it with:
`const numberOfStudents = class07Students.length`
your solution works. Good call with the "lowercase" on the queen :).

Good job ⭐️

Olivier

**Comment by bengu-thon-mai-mochi** [comment]
Hello Olivier,

Thank you for your time and feedback.
I had to start and finish my homework for this week very quick, so I didn't have time for refactoring and pushing changes to github. I did the changes you told me and it works 👍
