### ISSUE TITLE
Homework Feedback JS1-Week3

### ISSUE THREAD

**Issue by Swapna-Sahu** [bengu-thon-mai-mochi/hyf-homework#5]
Impressive work 🥇 . Waiting to see your creativity in optional task 👍 .
I have few comments for your homework : 

Good to see Spread Operator but here in this homework we are trying to use Push, Pop , Shift and Slice method . If you can change your code for adding song and use these method then it will be good.

SeriesDuration Task -
const humanLifeSpan = 80; no need to create this if you are passing parameters as number 80 instead humanLifeSpan
let humanLifeInMinutes = humanLifeMinute(80);

function serieToMinutes (obj) {
    let serieDayToMinute = (obj.days * day) * hour;
    let serieHourToMinute = obj.hours * hour;
    let seriesMinute = serieDayToMinute + serieHourToMinute + obj.minutes;
    return seriesMinute; 
}
let serieDayToMinute = (obj.days * day) * hour;
Ex - (1*24*60)*60*1  do u meant this? This is second 

Enjoy Coding 👍

**Comment by bengu-thon-mai-mochi** [comment]
Hi Swapna,

thanks a lot for the feedback. 
Refactored the code accordingly. 

:shipit:
